namespace _Project.CodeBase.Logic.Inventory
{
    public enum ItemName
    {
        None,
        AK47,
        M4A4,
        M40A5,
        Beretta,
        BarrettM82,
        GrenadeLauncher,
        TwoBarrelShotgun,
        Spas12,
        Glock17,
        Revolver,
        Ump45,
        Mp9,
        Flamethrower,
        Knife,
        PkpPecheneg,
        RifleAmmo,
        SniperAmmo,
        PistolAmmo,
        LmgAmmo,
        Vog25Ammo,
        ShotgunAmmo,
        FlameAmmo
    }
}